sudo: required
language: java
jdk:
  - oraclejdk8
node_js:
  - "7"
before_install:
  - npm config set registry http://registry.npmjs.org/
script:
  - ./gradlew build -Pacceptance

services:
  - docker
